application/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  resources :doc_templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "download_syllabus_excel" => "syllabuses#download_total_syllabus", as: "download_syllabus_excel"
  get "download_syllabus_evaluation_system" => "syllabuses#download_syllabus_evaluation_system", as: "download_syllabus_evaluation_system"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: :create
      resources :admin_sessions, only: :create do
        get "me" => "admin_sessions#me", as: "me", on: :collection
        post "refresh" => "admin_sessions#refresh", as: "refresh", on: :collection
      end
      resources :syllabuses, only: :index do
        collection do
          resources :syllabus_program, controller: "syllabuses", only: [:edit, :update, :show]
        end
        put "approve/:id" => "syllabuses#approve", as: "aprove_syllabus", on: :collection
        put "send_to_approve/:id" => "syllabuses#send_to_approve", as: "send_to_approve_syllabus", on: :collection
        put "refuse/:id" => "syllabuses#refuse", as: "refuse_syllabus", on: :collection
        put "set_obs_new/:id" => "syllabuses#set_obs_new", as: "set_obs_new_syllabus", on: :collection
        delete "remove_message_obs/:id_message" => "syllabuses#remove_message_obs", as: "remove_message_obs", on: :collection
        get "email_message_success" => "syllabuses#email_message_success", as: "email_message_success", on: :collection
        put "export_and_save/:id" => "syllabuses#export_and_save", as: "export_and_save", on: :collection
        get "export/:id" => "syllabuses#export", as: "export", on: :collection
        put "disable_modal/:id" => "syllabuses#disable_modal_to_syllabus", as: "disable_modal", on: :collection
        put "disable_modal_sidebar/:id" => "syllabuses#disable_modal_sidebar_to_syllabus", as: "disable_modal_sidebar", on: :collection
        ### Information Sources ########
        get "load_information_sources" => "syllabuses#load_information_sources", as: "load_information_sources", on: :collection
        get "search_information_sources" => "syllabuses#search_information_sources", as: "search_information_sources", on: :collection
        post "add_information_source" => "syllabuses#add_information_source", as: "add_information_source", on: :collection
        delete "remove_information_source/:id_information_source" => "syllabuses#remove_information_source", as: "remove_information_source", on: :collection
      end
      resources :dashboard, only: :index do
        get "filter_syllabuses" => "dashboard#filter_syllabuses", as: "filter_syllabuses", on: :collection
      end
      resources :sessions, only: :index do
        get "me" => "sessions#me", as: "me", on: :collection
        post "refresh" => "sessions#refresh", as: "refresh", on: :collection
      end
      resources :cycles do
        get "list" => "cycles#list", as: "list", on: :collection
        get "job_status" => "cycles#job_status", as: "job_status", on: :collection
        post "execute_copy" => "cycles#execute_copy", as: "execute_copy", on: :collection
      end
      resources :user_admins
      resources :syllabuses_admin do
        post "export_pdf" => "syllabuses_admin#export_pdf", as: "export_pdf", on: :collection
        post "export_pdf_collection" => "syllabuses_admin#export_pdf_collection", as: "export_pdf_collection", on: :collection
        post "update_states" => "syllabuses_admin#update_states", as: "update_states", on: :collection
        get "job_status" => "syllabuses_admin#job_status", as: "job_status", on: :collection
        post "cancel_export" => "syllabuses_admin#cancel_export", as: "cancel_export", on: :collection
        post "retry_export" => "syllabuses_admin#retry_export", as: "retry_export", on: :collection
      end
      resources :users
      resources :program_courses do
        post "cgt_course" => "program_courses#cgt_course", as: "cgt_course", on: :collection
        post "add_similar_course" => "program_courses#add_similar_course", as: "add_similar_course", on: :collection
      end
      resources :books
      resources :job_status
      resources :syllabus_programs do
        put "update_syllabus/:id" => "syllabus_programs#update_syllabus", as: "update_syllabus", on: :collection
        put "send_to_approve/:id" => "syllabus_programs#send_to_approve", as: "send_to_approve_syllabus_program", on: :collection
        put "observe/:id" => "syllabus_programs#observe", as: "observe_syllabus_program", on: :collection
        put "approve/:id" => "syllabus_programs#approve", as: "approve_syllabus_program", on: :collection
        post "request_edit/:id" => "syllabus_programs#request_edit", as: "request_edit_syllabus_program", on: :collection
        put "request_edition/:id" => "syllabus_programs#request_edition", as: "request_edition_syllabus_program", on: :collection
        put "update_text/:id" => "syllabus_programs#update_text", as: "update_text", on: :collection
        put "update_flags/:id" => "syllabus_programs#update_flags", as: "update_flags", on: :collection
        post "/:id/observations" => "syllabus_programs#create_observation", as: "create_observation_syllabus", on: :collection
        put "/observations/:id" => "syllabus_programs#update_observation", as: "update_observation_syllabus", on: :collection
        delete "/observations/:id" => "syllabus_programs#destroy_observation", as: "delete_observation_syllabus", on: :collection
        post "/:id/export_pdf" => "syllabus_programs#export_pdf", as: "export_pdf_syllabus", on: :collection
      end
      resources :practices
      resources :laboratories
      resources :general_competitions do
        post "/import_courses" => "general_competitions#import_courses", as: "general_competitions_import_courses", on: :collection
      end
      resources :specific_competitions do
        post "import" => "specific_competitions#import", as: "import_specific_competitions", on: :collection
      end
      resources :careers do
        post "/:id/import_competences" => "careers#import_competences", as: "career_import_competences", on: :collection
        post "/:id/remove_competences" => "careers#remove_competences", as: "career_remove_competences", on: :collection
        put "/:id/update_courses" => "careers#update_courses", as: "career_update_courses", on: :collection
        post "/:id/courses" => "careers#courses", as: "career_courses", on: :collection
      end
    end
  end

  mount ActionCable.server, at: "/cable"
end

application/app/models/course.rb
class Course < ApplicationRecord
  has_many :information_sources, :dependent => :destroy, :inverse_of => :course
  has_many :books, :through => :information_sources
  has_many :competitions

  belongs_to :course_dependent, class_name: "Course", foreign_key: "course_id_requeriment", optional: true
  has_many :requirements, class_name: "Course", foreign_key: "course_id_requeriment"

  has_and_belongs_to_many :faculties
  has_many :program_courses
  has_many :syllabuses

  def information_sources_ordered_asc
    information_sources.order_by_type_source.includes(:book)
  end

  def basic_book_ids
    information_sources.basic.pluck(:book_id)
  end

  def complementary_book_ids
    information_sources.complementary.pluck(:book_id)
  end

  def current_syllabus
    current_syllabus = syllabuses.active
  end

  def modalities
    program_courses.pluck(:modality_id)
  end

  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file)
    errors = []
    courses_count = 0
    return { errors: ["Documento vacío. Debe ingresar un archivo con la estructura correcta"], courses_count: 0, error_type: "invalid_document" } if spreadsheet.first_row.nil?
    all_headers = spreadsheet.row(6)
    unless all_headers.size == 17
      return { errors: ["No se han considerado todas las columnas. Debe ingresar un archivo con la estructura correcta"], courses_count: 0, error_type: "invalid_document" }
    end
    (7..spreadsheet.last_row).each do |i|
      course = Course.new
      course.for_all_career = spreadsheet.row(i)[4].present? ? I18n.transliterate(spreadsheet.row(i)[4].to_s).downcase.strip.eql?("si") : false
      course.for_all_faculties = spreadsheet.row(i)[5].present? ? I18n.transliterate(spreadsheet.row(i)[5].to_s).downcase.strip.eql?("si") : false
      code_in_person = spreadsheet.row(i)[0].to_s
      code_in_person.strip! if code_in_person.present?
      credits_in_person = spreadsheet.row(i)[13]
      w_hours_in_person = spreadsheet.row(i)[15]
      supervisor = User.search_user_by_email(spreadsheet.row(i)[6].to_s)
      if supervisor.nil?
        errors << "Error en la Fila #{i}: Ingrese un email de aprobador existente"
        next
      end
      coordinator_preg = User.search_user_by_email(spreadsheet.row(i)[7].to_s)
      if coordinator_preg.nil?
        errors << "Error en la Fila #{i}: Ingrese un email de editor PREG existente"
        next
      end
      name_in_person = spreadsheet.row(i)[2].to_s
      name_in_person.strip! if name_in_person.present?
      course.program_courses.build(catalog_code: code_in_person, type: "InPerson", name: name_in_person, credits: credits_in_person, weekly_hours: w_hours_in_person, coordinator_id: coordinator_preg.id, supervisor_id: supervisor.id)
      code_blended = spreadsheet.row(i)[1].to_s
      unless code_blended.blank?
        code_blended.strip!
        coordinator_cgt = User.search_user_by_email(spreadsheet.row(i)[8].to_s)
        if coordinator_cgt.nil?
          errors << "Error en la Fila #{i}: Ingrese un email de editor CGT existente"
          next
        end
        name_blended = spreadsheet.row(i)[3].blank? ? name_in_person : spreadsheet.row(i)[3].to_s
        name_blended.strip!
        credits_blended = spreadsheet.row(i)[14]
        w_hours_blended = spreadsheet.row(i)[16]
        course.program_courses.build(catalog_code: code_blended, type: "Blended", name: name_blended, credits: credits_blended, weekly_hours: w_hours_blended, coordinator_id: coordinator_cgt.id, supervisor_id: supervisor.id)
      end
      s = nil
      begin
        if course.save!
          s = Syllabus.new
          s.cycle_id = Cycle.active.id
          s.cycle_academic = REGULAR_CYCLE
          s.year = 2020
          s.doc_template_id = 1
          s.curriculum_course_id = 1
          s.course = course
          fundamentation = spreadsheet.row(i)[9].to_s[0..1349] unless spreadsheet.row(i)[9].blank?
          summary = spreadsheet.row(i)[10].to_s[0..999] unless spreadsheet.row(i)[10].blank?
          achievement = spreadsheet.row(i)[11].to_s[0..999] unless spreadsheet.row(i)[11].blank?
          methodology = spreadsheet.row(i)[12].to_s[0..1799] unless spreadsheet.row(i)[12].blank?
          s.syllabus_content = Syllabus.set_content_json_silabus(fundamentation, summary, achievement)
          json_units = { units: [], texts: [Syllabus.populate_methodology_json_text(methodology)] }.to_json

          course.program_courses.each do |p_course|
            syllabus_param_hash = {
              program_json: JSON.parse(json_units),
              type_program: p_course.is_a?(InPerson) ? TYPE_PROGRAM_PREGRADO : TYPE_PROGRAM_CGT,
              state: NO_READ_STATE,
              coordinator_id: p_course.is_a?(InPerson) ? coordinator_preg.id : coordinator_cgt.id,
              supervisor_id: supervisor.id,
              modality_id: p_course.is_a?(InPerson) ? PRESENCIAL_CODE : SEMI_PRESENCIAL_CODE,
              evaluation_system_json: { evaluation_system: [] },
              evaluation_rules_json: { rules: [] },
            }
            s.syllabus_programs.build(syllabus_param_hash)
            s.save!
            courses_count += 1
          end
        end
      rescue ActiveRecord::RecordInvalid => invalid
        error_obj = course.program_courses.first.errors.full_messages.empty? ? course.program_courses.last : course.program_courses.first
        errors << "Error en la Fila #{i}: #{error_obj.errors.full_messages.first}"
        next
      rescue Exception => e
        errors << "Error en la Fila #{i}: #{e.message}"
        next
      end

      # course_pregrade = ProgramCourse.search_course_by_catalog_code(code_pregrade)
      # unless course_pregrade.present?
      # else
      # errors << ""
      # end

    end
    { errors: errors, courses_count: courses_count }
  end
end

application/app/views/admin/program_courses/_error_message.html.erb
<div class="alert alert-dismissable alert-danger" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  
  <div class="alert-content">
  	<span class="icon-next">
    	<i class="alert-icon fa fa-exclamation-circle"></i>
    </span>
    <div class="errors-list-content">
	    <h3> <%= error["title"].html_safe %> </h3>
	    <p> <%= error["message"].html_safe %> </p>
    </div>
  </div>
</div>

application/app/views/admin/program_courses/_show_modal.html.erb
<div id="upload-courses-modal" class="modal fade" tabindex="-1" role="dialog">
  <%= form_with(url: import_courses_program_courses_admin_index_path, local: true, multipart: true, html: { id: "upload-courses-form" }) do |form| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content" data-context>
        <div class="modal-header">
          <h4 class="modal-title">Importar cursos</h4>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <%= form.file_field :file, required: true, accept: 'application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/x-ole-storage'%><br/><br/>
          <%= link_to 'Descargar Plantilla', asset_path('Nueva_plantilla_cursos_silabos.xlsx'), class: 'btn btn-primary btn-fill' %>
        </div>
        <div class="modal-footer">
          <div class="custom-loading-spinner">
            <div class="sk-chase">
              <div class="sk-chase-dot"></div>
              <div class="sk-chase-dot"></div>
              <div class="sk-chase-dot"></div>
              <div class="sk-chase-dot"></div>
              <div class="sk-chase-dot"></div>
              <div class="sk-chase-dot"></div>
            </div>
          </div>
         
          <%= submit_tag "Cargar cursos", data: {disable_with: "Cargando... " }, id: 'submit-courses-button', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

application/app/views/admin/program_courses/_success_import_message.html.erb
<div class="alert alert-dismissable alert-info" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  <div class="alert-content">
  	<span class="icon-next">
    	<i class="alert-icon fa fa-check-circle"></i>
    </span>
    <div class="errors-list-content">
	    <h3> <%= result["title"].html_safe %> </h3>
	    <p> <%= result["message"].html_safe %> </p>
    </div>
  </div>
</div>

application/app/views/admin/program_courses/cgt_course.html.erb
<div id="new-cgt-course-modal" >
  <%= form_with(model: @cgt_course, url: cgt_course_program_courses_admin_path, local: true, multipart: true, html: { id: "new-cgt-course-form" }) do |form| %>
    <div class="modal-content" data-context>
      <div class="modal-header">
        <h4 class="modal-title">Crear Curso CGT</h4>
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
      </div>
      <div>
        <%= render 'error_message', error: @error_cgt_hash if @error_cgt_hash.present? %>
      </div>
      <div class="modal-body">
        <div class="main-content">
          <div class="form-group row">
            <div class="col-sm-6">
              <%= form.label :catalog_code, {class: "control-label"} %>
              <%= form.text_field :catalog_code, {class: "form-control", required: true, maxlength: 10} %>
            </div>
            <div class="col-sm-6">
              <%= form.label :name, {class: "control-label"} %>
              <%= form.text_field :name, {class: "form-control", required: true} %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6">
              <%= form.label :weekly_hours, {class: "control-label", required: true} %>
              <%= form.number_field :weekly_hours, {class: "form-control", required: true, maxlength: 2, min: 1, max:99} %>
            </div>
            <div class="col-sm-6">
              <%= form.label :credits, {class: "control-label"} %>
              <%= form.number_field :credits, {class: "form-control", required: true, maxlength: 2, min: 1, max:99} %>
            </div>
          </div>
          <div class="form-group">
            <%= form.label :coordinator_id, {class: "control-label", required: true} %>
            <%= form.select :coordinator_id,User.active.with_role(ROLE_CREATOR.to_sym).map { |user| [user.name, user.id]}, {class: "form-control", required: true} %>
          </div>
          <div class="form-group">
            <%= form.label :supervisor_id, {class: "control-label"} %>
            <%= form.select :supervisor_id,User.active.with_role(ROLE_APPROVER.to_sym).map { |user| [user.name, user.id]}, {class: "form-control", required: true} %>
          </div>
          <%= form.hidden_field :course_id, id: 'course-field' %>
        </div>
      </div>
      <div class="modal-footer">
        <div class="custom-cgt-form-loading-spinner">
          <div class="sk-chase">
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
            <div class="sk-chase-dot"></div>
          </div>
        </div>
       
        <%= submit_tag "Crear curso", data: {disable_with: "Cargando... " }, id: 'create-cgt-course-button', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".modal.fade.in").removeAttr("tabindex");
    $("#blended_coordinator_id").select2({theme: 'bootstrap'});
    $("#blended_supervisor_id").select2({theme: 'bootstrap'});
    
    $(".custom-cgt-form-loading-spinner").hide();
    $("#upload-courses-form").on("submit", function(){
      $(".custom-loading-spinner").show();
    });//submit
  });//document ready
</script>

application/app/views/admin/program_courses/index.html.erb
<% content_for(:title, "Listado de cursos") %>

<% toolbar(:primary) do |t| %>
  <button type="button" class="btn btn-primary btn-fill pull-right" style="margin-right: 5px;" data-toggle="modal" data-target="#upload-courses-modal">
    <i class="far fa-file-excel" aria-hidden="true"></i> Importar Cursos
  </button>
<% end %>
<%=  render 'show_modal' %>
<div>
  <%= render 'success_import_message', result: flash[:result_hash] if flash[:result_hash].present? %>
</div>
<div>
  <%= render 'error_message', error: flash[:error_hash] if flash[:error_hash].present? %>
</div>

<% content_for(:utilities) do %>
  <%= render "scopes" if admin.scopes.any? %>
<% end if admin.scopes.any? %>

<%= render layout: "layout" do %>
  <header class="main-content-header">
    <div class="searchbox">
      <%= form_tag "/program_courses", method: :get do %>
        <%= hidden_field_tag :scope, params[:scope] %>
        <div class="input-group">
          <span class="input-group-text"><icon class="fa fa-search"></icon></span>
          <%= link_to icon("fa fa-times"), admin.path, class: "clear-search" if params[:q].present? %>
          <%= search_field_tag :q, params[:q], class: "form-control", autocomplete: "off", placeholder: "Ingrese el nombre o código de catálogo" %>
        </div>
      <% end %>
    </div>
  </header>

  <%= render "trestle/table/table", table: admin.table, collection: collection %>

  <footer class="main-content-footer">
    <%= hook("resource.index.footer") %>

    <%= render "trestle/table/pagination", collection: collection, entry_name: admin.model_name %>
  </footer>
<% end %>
<script type="text/javascript">
  $(document).ready(function(){
    $(".custom-loading-spinner").hide();
    $("#upload-courses-form").on("submit", function(){
      $(".custom-loading-spinner").show();
    });//submit
    if ("<%=flash[:show_dialog]%>"=="true") {
      const dialog = new Trestle.Dialog({
      modalClass: $(this).data('dialog-class')
      })
      dialog.load("/program_courses/"+"<%=flash[:in_person_id]%>/cgt_course?cgt_name=<%=flash[:cgt_name]%>&cgt_coordinator=<%=flash[:cgt_coordinator]%>&cgt_supervisor=<%=flash[:cgt_supervisor]%>&cgt_weekly_hours=<%=flash[:cgt_weekly_hours]%>&cgt_credits=<%=flash[:cgt_credits]%>&cgt_catalog_code=<%=flash[:cgt_catalog_code]%>&cgt_error=<%=flash[:cgt_error]%>")
    }
    
  });//document ready
</script>

application/app/views/admin/program_courses/show.html.erb
<%= form_with(model: @program_course, url:program_courses_admin_path(@program_course), local: true) do |form| %>

	<header class="content-header">
	  <div class="content-header-title">
	    <h1>
	      Detalle de curso
	    </h1>
	  </div>
	  <div class="content-header-toolbars">
	    <div class="btn-toolbar primary-toolbar">
	      <button name="button" type="submit" class="btn btn-success"><span class="btn-label">Guardar curso</span></button>
	      
	    </div>
	  </div>
	</header>

	<% if flash[:error] %>
		<div class="alert alert-dismissable alert-danger" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
		  
		  <div class="alert-content">
		  	<span class="icon-next">
		    	<i class="alert-icon ion-android-alert"></i>
		    </span>
		    <div class="errors-list-content">
			    <h3> Ocurrió un error al guardar el curso: </h3>
			    <p> <%= flash[:error] %> </p>
		    </div>
		  </div>
		</div>
	<% end %>
	<div>
	  <div>
		  <% if flash[:message] %>
			  <div class="alert alert-dismissable alert-info" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <%= icon %>

				  <div class="alert-content">
				    <% if flash[:message]["title"] %>
				      <h3><%= flash[:message]["title"] %></h3>
				    <% end %>

				    <p><%= flash[:message]["message"] %></p>

				    <%= yield if block_given? %>
				  </div>
				</div>
		  <% end %>
		</div>
	</div>
	<div class="main-content-area">
    <div class="main-content-container">
      <div class="main-content">
			  <div class="form-group">
			    <%= form.label :catalog_code, {class: "control-label"} %>
			    <%= form.text_field :catalog_code, {class: "form-control"} %>
			  </div>
			  <div class="form-group">
			    <%= form.label :name, {class: "control-label"} %>
			    <%= form.text_field :name, {class: "form-control"} %>
			  </div>
			  <div class="form-group">
			    <%= label_tag :modalidad, "Modalidad", {class: "control-label"} %>
			    <p class="form-control-static"> <%=@program_course.human_type%> </p>
			  </div>
			  <div class="form-group">
			    <%= form.label :coordinator_id, {class: "control-label"} %>
			    <%= form.select :coordinator_id,User.active.with_role(ROLE_CREATOR.to_sym).map { |user| [user.name, user.id]}, {class: "form-control"} %>
			  </div>
			  <div class="form-group">
			    <%= form.label :supervisor_id, {class: "control-label"} %>
			    <%= form.select :supervisor_id,User.active.with_role(ROLE_APPROVER.to_sym).map { |user| [user.name, user.id]}, {class: "form-control"} %>
			  </div>
			  <div class="form-group">
			    <%= form.label :weekly_hours, {class: "control-label"} %>
			    <%= form.number_field :weekly_hours, {class: "form-control", min: 1, max:99} %>
			  </div>
			  <div class="form-group">
			    <%= form.label :credits, {class: "control-label"} %>
			    <%= form.number_field :credits, {class: "form-control", min: 1, max:99} %>
			  </div>
			  <div class="form-group">
			    <%= form.label :authorized, {class: "control-label"} %>
			    <%= form.check_box :authorized, {class: "form-control"} %>
			  </div>
			  <div class="form-group">
			  	<%= label_tag :book_ids, "Libros", {class: "control-label"} %>
					<% unless @similar_course.nil? %>
						<p>*Recuerda que al editar los libros de este curso se editarán automáticamente los del curso <b><%=@similar_course.code_type%> <%= @similar_course.name%></b>*</p>
					<%end%>
					<div class="form-group" style="margin-left: 20px">
						<%= label_tag :book_basic_ids, "Básicos", {class: "control-label"} %>
						<p>Puedes agregar un máximo de 3 libros.</p>
				  	<%= select_tag 'book_basic_ids', options_for_select(@book_basic_ids.map { |book| [book.label_for_tag, book.id] }, @book_basic_ids.pluck(:id)), multiple: true, size: 1, class: "form-control" %>
				  </div>
				  <div class="form-group" style="margin-left: 20px">
						<%= label_tag :book_complementary_ids, "Complementarios", {class: "control-label"} %>
						<p>No tiene máximo de libros.</p>
				  	<%= select_tag 'book_complementary_ids', options_for_select(@book_complementary_ids.map { |book| [book.label_for_tag, book.id] }, @book_complementary_ids.pluck(:id)), multiple: true, size: 10, class: "form-control" %>
				  </div>
			  </div>

      </div>
    </div>
  </div>
<%end%>