application/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  resources :doc_templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "download_syllabus_excel" => "syllabuses#download_total_syllabus", as: "download_syllabus_excel"
  get "download_syllabus_evaluation_system" => "syllabuses#download_syllabus_evaluation_system", as: "download_syllabus_evaluation_system"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: :create
      resources :admin_sessions, only: :create do
        get "me" => "admin_sessions#me", as: "me", on: :collection
        post "refresh" => "admin_sessions#refresh", as: "refresh", on: :collection
      end
      resources :syllabuses, only: :index do
        collection do
          resources :syllabus_program, controller: "syllabuses", only: [:edit, :update, :show]
        end
        put "approve/:id" => "syllabuses#approve", as: "aprove_syllabus", on: :collection
        put "send_to_approve/:id" => "syllabuses#send_to_approve", as: "send_to_approve_syllabus", on: :collection
        put "refuse/:id" => "syllabuses#refuse", as: "refuse_syllabus", on: :collection
        put "set_obs_new/:id" => "syllabuses#set_obs_new", as: "set_obs_new_syllabus", on: :collection
        delete "remove_message_obs/:id_message" => "syllabuses#remove_message_obs", as: "remove_message_obs", on: :collection
        get "email_message_success" => "syllabuses#email_message_success", as: "email_message_success", on: :collection
        put "export_and_save/:id" => "syllabuses#export_and_save", as: "export_and_save", on: :collection
        get "export/:id" => "syllabuses#export", as: "export", on: :collection
        put "disable_modal/:id" => "syllabuses#disable_modal_to_syllabus", as: "disable_modal", on: :collection
        put "disable_modal_sidebar/:id" => "syllabuses#disable_modal_sidebar_to_syllabus", as: "disable_modal_sidebar", on: :collection
        ### Information Sources ########
        get "load_information_sources" => "syllabuses#load_information_sources", as: "load_information_sources", on: :collection
        get "search_information_sources" => "syllabuses#search_information_sources", as: "search_information_sources", on: :collection
        post "add_information_source" => "syllabuses#add_information_source", as: "add_information_source", on: :collection
        delete "remove_information_source/:id_information_source" => "syllabuses#remove_information_source", as: "remove_information_source", on: :collection
      end
      resources :dashboard, only: :index do
        get "filter_syllabuses" => "dashboard#filter_syllabuses", as: "filter_syllabuses", on: :collection
      end
      resources :sessions, only: :index do
        get "me" => "sessions#me", as: "me", on: :collection
        post "refresh" => "sessions#refresh", as: "refresh", on: :collection
      end
      resources :cycles do
        get "list" => "cycles#list", as: "list", on: :collection
        get "job_status" => "cycles#job_status", as: "job_status", on: :collection
        post "execute_copy" => "cycles#execute_copy", as: "execute_copy", on: :collection
      end
      resources :user_admins
      resources :syllabuses_admin do
        post "export_pdf" => "syllabuses_admin#export_pdf", as: "export_pdf", on: :collection
        post "export_pdf_collection" => "syllabuses_admin#export_pdf_collection", as: "export_pdf_collection", on: :collection
        post "update_states" => "syllabuses_admin#update_states", as: "update_states", on: :collection
        get "job_status" => "syllabuses_admin#job_status", as: "job_status", on: :collection
        post "cancel_export" => "syllabuses_admin#cancel_export", as: "cancel_export", on: :collection
        post "retry_export" => "syllabuses_admin#retry_export", as: "retry_export", on: :collection
      end
      resources :users
      resources :program_courses do
        post "cgt_course" => "program_courses#cgt_course", as: "cgt_course", on: :collection
        post "add_similar_course" => "program_courses#add_similar_course", as: "add_similar_course", on: :collection
      end
      resources :books
      resources :job_status
      resources :syllabus_programs do
        put "update_syllabus/:id" => "syllabus_programs#update_syllabus", as: "update_syllabus", on: :collection
        put "send_to_approve/:id" => "syllabus_programs#send_to_approve", as: "send_to_approve_syllabus_program", on: :collection
        put "observe/:id" => "syllabus_programs#observe", as: "observe_syllabus_program", on: :collection
        put "approve/:id" => "syllabus_programs#approve", as: "approve_syllabus_program", on: :collection
        post "request_edit/:id" => "syllabus_programs#request_edit", as: "request_edit_syllabus_program", on: :collection
        put "request_edition/:id" => "syllabus_programs#request_edition", as: "request_edition_syllabus_program", on: :collection
        put "update_text/:id" => "syllabus_programs#update_text", as: "update_text", on: :collection
        put "update_flags/:id" => "syllabus_programs#update_flags", as: "update_flags", on: :collection
        post "/:id/observations" => "syllabus_programs#create_observation", as: "create_observation_syllabus", on: :collection
        put "/observations/:id" => "syllabus_programs#update_observation", as: "update_observation_syllabus", on: :collection
        delete "/observations/:id" => "syllabus_programs#destroy_observation", as: "delete_observation_syllabus", on: :collection
        post "/:id/export_pdf" => "syllabus_programs#export_pdf", as: "export_pdf_syllabus", on: :collection
      end
      resources :practices
      resources :laboratories
      resources :general_competitions do
        post "/import_courses" => "general_competitions#import_courses", as: "general_competitions_import_courses", on: :collection
      end
      resources :specific_competitions do
        post "import" => "specific_competitions#import", as: "import_specific_competitions", on: :collection
      end
      resources :careers do
        post "/:id/import_competences" => "careers#import_competences", as: "career_import_competences", on: :collection
        post "/:id/remove_competences" => "careers#remove_competences", as: "career_remove_competences", on: :collection
        put "/:id/update_courses" => "careers#update_courses", as: "career_update_courses", on: :collection
        post "/:id/courses" => "careers#courses", as: "career_courses", on: :collection
      end
    end
  end

  mount ActionCable.server, at: "/cable"
end

application/app/models/cycle.rb
class Cycle < ApplicationRecord
  has_many :syllabuses, :dependent => :destroy
  has_many :modality_cycles, :dependent => :destroy
  has_many :modalities, :through => :modality_cycles
  validates :name, :cycle_start, :cycle_end, :type_cycle, presence: { message: "es requerido" }
  validates :enabled, inclusion: { in: [true, false] }
  validates :name, uniqueness: { case_sensitive: false, message: "Ciclo con el mismo nombre ya existe" }
  accepts_nested_attributes_for :modality_cycles

  scope :active, -> { where(:enabled => true).empty? ? last : where(:enabled => true).first }

  scope :inactive, -> { where(:enabled => false) }

  validate :end_date_after_start_date
  extend Enumerize
  enumerize :type_cycle, in: { :regular => REGULAR_CYCLE, :verano => SUMMER_CYCLE }

  after_save :update_enable_cycles

  def can_delete
    self.syllabuses.count == 0 && !self.enabled ? true : false
  end

  def human_type_cycle
    case type_cycle
    when REGULAR_CYCLE
      "Ciclo Regular"
    when SUMMER_CYCLE
      "Ciclo de Verano"
    else nil
    end
  end

  def update_enable_cycles
    Cycle.where(enabled: true).where.not(id: self.id).update_all(enabled: false) if self.enabled
  end

  def can_disable
    self.enabled ? false : true
  end

  def total_syllabus
    SyllabusProgram.number_of_syllabuses(self.id)
  end

  private

  def end_date_after_start_date
    return if cycle_end.blank? || cycle_start.blank?

    if cycle_end < cycle_start
      errors.add(:cycle_end, "debe ser posterior a la fecha de inicio")
    end
  end

  def enabled_cycle_with_end_date
    return if cycle_end.blank? || cycle_start.blank?
    if ((cycle_end.to_date < Time.now.to_date) && (enabled.present?))
      errors.add(:cycle_end, "debe ser mayor o igual al dia de hoy, si va habilitar el ciclo")
    end
  end
end

application/app/views/admin/syllabus_programs/_error_message.html.erb
<div class="alert alert-dismissable alert-danger" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  
  <div class="alert-content">
  	<span class="icon-next">
    	<i class="alert-icon fa fa-exclamation-circle"></i>
    </span>
    <div class="errors-list-content">
	    <h3> <%= error["title"].html_safe %> </h3>
	    <p> <%= error["message"].html_safe %> </p>
    </div>
  </div>
</div>

application/app/views/admin/syllabus_programs/_modal_download.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(url: collection_download_syllabus_programs_admin_index_path, html: { id: "download-syllabuses-form" }) do |form| %>
        <div class="progress-container">
          <%= image_tag 'icons/silb_arrow.svg', id:"downloading-icon"  %>
          <%= image_tag 'icons/silb_error.svg', id:"error-download-icon"  %>
          <%= image_tag 'icons/silb_success.svg', id:"success-download-icon"  %>
          <div id="download-progress-bar">
          </div>
        </div>
        <p id="download-descriptor">Estás a punto de descargar <%= @syllabuses_ids_valid.size%> sílabos</p>
        <% if @syllabuses_invalid_count > 0 %>
          <p id="additional-message-warn" class="message-download"><%= @syllabuses_invalid_count > 1 ? "#{@syllabuses_invalid_count} documentos no están disponibles para descarga." : "Un documento no está disponible para descarga"%> </p>
        <% end %>
        <p id="additional-message-info" class="message-download"></p>
        <div class="buttons-container">
          <%= form.submit 'Descargar', class: "download-button", id:"start-download-button"%>
          <button id="cancel-download-button" type="button" class="cancel-button" data-dismiss="modal"><span aria-hidden="true">Cancelar</span></button>
        </div>
        <% @syllabuses_ids_valid.each do |id| %>
          <%= form.hidden_field :syllabus_ids, id: 'syllabus-ids', multiple: true, value: id %>
        <% end %>
        
    <% end %>
    <div class="progress-actions-container"><div>
  </div>
</div>
<script type="text/javascript">
  $("#error-download-icon").hide()
  $("#success-download-icon").hide()
  $("#additional-message-info").hide();
  $(document).on('hidden.bs.modal', '#show-modal-download', function () { 
    $("#show-modal-download").remove(); 
  });
  var progressBar = new ProgressBar.Circle('#download-progress-bar', {
    strokeWidth: 6,
    easing: 'easeInOut',
    duration: 1400,
    color: '#3990f7',
    trailColor: '#979797',
    trailWidth: 6,
    svgStyle: null
  });


</script>

application/app/views/admin/syllabus_programs/_show_modal.html.erb
<div id="upload-courses-modal" class="modal fade" tabindex="-1" role="dialog">
  <%= form_with(url: update_general_achievement_syllabus_programs_admin_index_path, local: true, multipart: true, html: { id: "upload-courses-form" }) do |form| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content" data-context>
        <div class="modal-header">
          <h4 class="modal-title">Actualizar Logros</h4>
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <%= form.file_field :file, required: true, accept: ".csv" %><br/><br/>
          <!--<%= link_to "Descargar Plantilla", asset_path("Nueva_plantilla_cursos_silabos.xlsx"), class: "btn btn-primary btn-fill" %>-->
        </div>
        <div class="modal-footer">         
          <%= submit_tag "Cargar cursos", data: { disable_with: "Cargando... " }, id: "submit-courses-button", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

application/app/views/admin/syllabus_programs/_success_import_message.html.erb
<div class="alert alert-dismissable alert-info" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  <div class="alert-content">
  	<span class="icon-next">
    	<i class="alert-icon fa fa-check-circle"></i>
    </span>
    <div class="errors-list-content">
	    <h3> <%= result["title"].html_safe %> </h3>
	    <p> <%= result["message"].html_safe %> </p>
    </div>
  </div>
</div>

application/app/views/admin/syllabus_programs/collection_download.js.erb
var interval;
var original_color = "#979797"
var loaded_color = "#3990f7"
var success_color = "#43c889"
var error_color = "#ff8389"
var info_messages = ["Paciencia. Puede tardar unos minutos.", "Descargando.", "Ya no falta mucho.", "Si cierra esta ventana no podrá descargar los sílabos."];
var messages_index = 0;
$("#start-download-button").hide();
$("#cancel-download-button").hide();
$("#additional-message-warn").hide();
$("#additional-message-info").show();
$("#download-descriptor").text("Obteniendo tus archivos...")
$("#additional-message-info").text(info_messages[messages_index]);
interval = setInterval(function(){
  $.ajax("syllabus_programs/job_status/",{
    success: function(job){
      console.log(job);
      var stage, progress;
      if (job.completed) {
        successful_download(job)
      }else{
        if (job.progress < job.max_progress){
          $("#additional-message-info").text(info_messages[messages_index % 4]);
          messages_index++;
          let progress_num = job.progress / job.max_progress
          progressBar.animate(progress_num)
          $("#download-descriptor").text(job.message)
        }else{
          progressBar.animate(1)
          $("#download-descriptor").text(job.message)
        }
      }
    },
    error: function(){
      // Job is no loger in database which means it finished successfuly
      console.log("error")
      $("#download-descriptor").text("¡Ups!")
      $("#additional-message-info").text("Hubo un error en la descarga. Cierre la ventana e intente de nuevo.")
      $("#downloading-icon").hide()
      $("#error-download-icon").show()
      clearInterval(interval);
      progressBar.animate(1, {
        from: { color: loaded_color },
        to: { color: error_color },
        step: function(state, bar) {
            bar.path.setAttribute('stroke', state.color);
        }
      });
    }
  })
},2000);

function successful_download(job) {
  clearInterval(interval);
  var modal_visible = ($("#show-modal-download").data('bs.modal') || {})._isShown;
  if(modal_visible){
    progressBar.animate(1, {
      from: { color: loaded_color },
      to: { color: success_color },
      step: function(state, bar) {
          bar.path.setAttribute('stroke', state.color);
      }
    });
    $("#download-descriptor").text("¡Gracias por esperar!")
    $("#success-download-icon").show()
    $("#downloading-icon").hide()
    $("#cancel-download-button").hide();
    $("#additional-message-info").text("La descarga ha sido un éxito.")
    location.href = `${job.generated_zip_path}`;
  }else{
    console.log("Modal closed");
  }
  
}

application/app/views/admin/syllabus_programs/index.html.erb
<% content_for(:title, "Listado de sílabos") %>
<% toolbar(:primary) do |t| %>
  <button type="button" class="btn btn-primary btn-fill pull-right" style="margin-right: 5px;" data-toggle="modal" data-target="#upload-courses-modal">
    <i class="far fa-file-excel" aria-hidden="true"></i> Actualizar logros
  </button>
<% end %>
<%= render "show_modal" %>
<div>
  <%= render "success_import_message", result: flash[:result_hash] if flash[:result_hash].present? %>
</div>
<div>
  <%= render "error_message", error: flash[:error_hash] if flash[:error_hash].present? %>
</div>
<% content_for(:utilities) do %>
  <%= render "scopes" if admin.scopes.any? %>
  <%= link_to "Descargar silabos", show_modal_download_syllabus_programs_admin_index_path(:q => params[:q], updated_at: params[:updated_at], supervisor_id: params[:supervisor_id]), class: "show-syllabus-modal", remote: true if params[:scope].present? && params[:scope] == "approved" && @able_to_download_count > 0 %>
  <%= link_to "Descargar silabos", "", class: "show-syllabus-modal disabled-show-modal", remote: true if params[:scope].present? && params[:scope] == "approved" && @able_to_download_count == 0 %>
<% end if admin.scopes.any? %>

<%= render layout: "layout" do %>
  <header class="main-content-header">
    <div class="searchbox" style="max-width: none">
        <div class="row">
          <div class="col-md-9">
            <%= form_tag "/syllabus_programs", method: :get do %>
              <%= hidden_field_tag :scope, params[:scope] %>
              <div class="row">
                <div class="col-md-4">
                  <div class="input-group">
                    <span class="input-group-text"><icon class="fa fa-search"></icon></span>
                    <%= link_to icon("fa fa-times"), admin.path, class: "clear-search" if params[:q].present? %>
                    <%= search_field_tag :q, params[:q], class: "form-control", autocomplete: "off", placeholder: "Ingrese el nombre o código de catálogo" %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="input-group">
                    <%= text_field_tag :updated_at, params[:updated_at], id: "updated-at-filter", placeholder: "Fecha de último cambio", class: "form-control datetimepicker-input", autocomplete: "off", data: { toggle: "datetimepicker", target: "#updated-at-filter" } %>
                  </div>
                </div>
                <div class="col-md-3">
                  <%= select_tag :supervisor_id, options_for_select(User.active.with_role(ROLE_APPROVER.to_sym).map { |user| [user.name, user.id] }, params[:supervisor_id]), prompt: "Selecciona un aprobador" %>
                </div>
                <div class="col-md-2">
                  <button name="button" type="submit" class="btn btn-success"><span class="btn-label">Filtrar</span></button>
                </div>
              </div>
            <% end %>
          </div>
          <% unless params[:scope].blank? %>
            <div class="row col-md-3">
              <div class="col-md-9 offset-md-1">
                <%= select_tag :destiny_state, options_for_select(@scope_states, {}), prompt: "Selecciona el estado", required: "true", class: "custom-select" %>
              </div>
              <div class="col-md-2">
                <button name="button" type="submit" form="udpate_multiple_syllabuses" id="update-syllabus-button" class="btn btn-success" data-confirm="Seguro?"><span class="btn-label">Cambiar</span></button>
              </div>
              <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                      <p id="confirm-message"></p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" data-dismiss="modal" class="btn btn-default" id="modal-btn-no">Cancelar</button>
                      <button type="button" class="btn btn-primary" id="modal-btn-si">Aceptar</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </header>
  <%= form_tag "/syllabus_programs/update_states", id: "udpate_multiple_syllabuses", method: :post do %>
    <%= hidden_field_tag :selected_state, params[:selected_state] %>
    <%= hidden_field_tag "changing-states", false %>
    <% if params[:scope].present? && params[:scope] == "approved" %>
      <% if @able_to_download_count > 0 %>
        <div class="syllabuses-downloads-alert enabled-downloads row">
          <div class="ready-indication">
              <%= image_tag "icons/Icons _ Outline _ alert.svg" %>
          </div>
          <div class="message">
            <span class="spanObs"><%= @able_to_download_count %> documentos están homologados y activos. Disponibles para descarga.</span>
          </div>
        </div>
      <% else %>
        <div class="syllabuses-downloads-alert disabled-downloads row">
          <div class="ready-indication">
              <%= image_tag src = "icons/alert-observations-top@3x.png" %>
          </div>
          <div class="message">
            <span class="spanObs">Estos documentos no están homologados y/o activos. No disponibles para descarga.</span>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= render "trestle/table/table", table: admin.table, collection: collection %>
  <% end %>

  <footer class="main-content-footer">
    <%= hook("resource.index.footer") %>

    <%= render "trestle/table/pagination", collection: collection, entry_name: admin.model_name %>
  </footer>
<% end %>
<script type="text/javascript">
  if ($(".datetimepicker-input").length) {
    if ("<%= !params[:updated_at].blank? %>") {
      var date = moment("<%= params[:updated_at] %>", 'DD/MM/YYYY hh:mm a').toDate();
      $(".datetimepicker-input").each(function(){
        $(this).datetimepicker({date: date, format: 'DD/MM/YYYY hh:mm a'});
      });
    }else{
      $(".datetimepicker-input").each(function(){
        $(this).datetimepicker({format: 'DD/MM/YYYY hh:mm a'});
      });
    }
    

    
  }
  
  manageUpdateSyllabusStatus();

  $("#supervisor_id").select2({theme: 'bootstrap'});
  let all_selected_check = $("thead > tr > th.select-row>input:checkbox");
  all_selected_check.change(function () {
    $("tbody > tr > td.select-row>input:checkbox").prop("checked", $(this).is(':checked'))
  })

  function manageUpdateSyllabusStatus() {
    any_checked = $("input:checkbox:checked").length > 0  
    $("#update-syllabus-button").prop('disabled', !any_checked);
    $("#destiny_state").prop('disabled', !any_checked);
  }

  $("input:checkbox").change(function(){
    manageUpdateSyllabusStatus();
  })

  $('#destiny_state').change(function() {
    var selected_state = $(this).val();
    $('#selected_state').val(selected_state);
  });

  function getConfirmData() {
    current_scope = "<%= @all_scopes[params[:scope]] %>"
    selected_state_list = $("#destiny_state")[0]
    selected_state = selected_state_list.options[selected_state_list.selectedIndex].innerHTML;
    checked_input_count = $("tbody > tr > td.select-row>input:checkbox:checked").length;
    sing_or_plur = checked_input_count > 1 ? "s." : "."
    return "Vas a modificar el estado de " + current_scope + " a "+selected_state+" en "+checked_input_count + " sílabo" + sing_or_plur
  }

  function showConfirmBox(message, cb) {
    var $modal = $('#mi-modal');
    var $btnYes = $modal.find('#modal-btn-si')
    $modal.find('#confirm-message').text(getConfirmData())
    $modal.modal();
    $btnYes.one('click', function(){
      $modal.modal('hide');
      cb(true);
    });

  }

  $(document).on('confirm', '[data-confirm]', function(e){
    var selected_state = $('#selected_state');
    var $el = $(this);
    if (selected_state.val()==="") {
      alert("Seleccione un estado destino antes de proceder con el cambio.");
      return false;
    }else{
      showConfirmBox($el.data('confirm'), function(confirmed){
        if (confirmed) {
          $('#changing-states').val(true);
          $el.data('confirm', null);
          var form = $('#udpate_multiple_syllabuses');
          form.submit();
          return true;
        }
      });
    }
    return false;
    
  });

  window.onbeforeunload = function(e) {
     checked_input_count = $("tbody > tr > td.select-row>input:checkbox:checked").length;
     changing_states = $("#changing-states").val();
     if (checked_input_count > 0 && changing_states!=="true") {
      toastr.error("Si sale de la página se perderán los sílabos seleccionados.",{showDuration: 1500});
      return "YES";
     }
  };


</script>

application/app/views/admin/syllabus_programs/show_modal_download.js.erb
var newModal = $("<div id=\"show-modal-download\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" ></div>" )
newModal.html('<%= escape_javascript render 'modal_download' %>');
newModal.appendTo( "body" );
newModal.modal();